test.property: devValue

application:
  servers:
    -   ip: '127.0.0.1'
        path: '/path1'
    -   ip: '127.0.0.2'
        path: '/path2'
    -   ip: '127.0.0.3'
        path: '/path3'


spring:
  datasource:
    password: password
    url: jdbc:h2:dev
    username: SA