version: '3'

services:

  mariadb:
    image: "mariadb:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - "MYSQL_DATABASE=barebone-jpa-app-database"
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
