openapi: 3.0.3

info:
  title: Company-API
  version: '2.1.0'

# For each distinct 'tags' property, a new '<tagsName>Api' interface will be created
# if the 'tags' are the same, all methods will be put in the same interface
# So, operation with the tag 'company' will be put in CompanyApi

paths:
  '/api/companies':
    get:
      operationId: getCompanies
      tags:
        - company
      responses:
        200:
          description: companies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'

  '/api/companies/{id}':
    get:
      operationId: getCompany
      tags:
        - company
      parameters:
        - in: path
          name: id
          example: "123"
          schema:
            type: string
          required: true
      responses:
        200:
          description: company
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        404:
          description: Company not found

components:
  headers: { }
  responses: { }
  parameters: { }
  schemas:

    Company:
      type: object
      properties:
        id:
          type: string
          example: "123"
        name:
          type: string
          example: "Google"
        parentCompany:
          type: string
          example: "Alphabet Inc."
          nullable: true
        departments:
          type: array
          example: "[\"marketing\", \"consulting\"]"
          items:
            type: string