openapi: 3.0.3

info:
  title: Company-API
  version: '2.1.0'

paths:
  '/api/companies':
    get:
      operationId: getCompanies
      tags:
        - companies
      responses:
        200:
          description: companies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'

  '/api/companies/{id}':
    get:
      operationId: getCompany
      tags:
        - companies
      parameters:
        - in: path
          name: id
          example: "123"
          schema:
            type: string
          required: true
      responses:
        200:
          description: company
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        404:
          description: Company not found

tags:
  - name: companies

servers:
  - url: 'https://www.leipziger-messe.de'

components:
  headers: { }
  responses: { }
  parameters: { }
  schemas:

    Company:
      type: object
      properties:
        id:
          type: string
          example: "123"
        name:
          type: string
          example: "Google"
        departments:
          type: array
          example: "[\"marketing\", \"consulting\"]"
          items:
            type: string