
// https://blog.pavelsklenar.com/jenkins-creating-dynamic-project-folders-with-job-dsl/
def folderName = "PROJECT_NAME".toUpperCase()
def adminGroup = "ROLE_${folderName}_ADMIN"
def opsGroup = "ROLE_${folderName}_READER"
folder(folderName) {
    displayName(folderName)
  description("Folder for project 'PROJECT_NAME' generated by 'JOB_NAME'")
    authorization {
        permissions(opsGroup, [
            'hudson.model.Item.Read',
            'hudson.model.View.Read'
        ])
        permissionAll(adminGroup) 
    }
}

listView('DEV') {
    description('DEV Jobs')
    // filterBuildQueue()
    // filterExecutors()
    jobs {
        // name('release-projectA')
        regex(/job-.*/)
    }
    // jobFilters {
    //     status {
    //         status(Status.UNSTABLE)
    //     }
    // }
    columns {
        status()
        weather()
        name()
        lastSuccess()
        lastFailure()
        lastDuration()
        buildButton()
    }
}

// pipelineJob('job-name') {
//   definition {
//     cps {
//       script(readFileFromWorkspace('./logic/job1.jenkinsfile'))
//       sandbox()     
//     }
//   }
// }

/*
// Inline alternative
*/
pipelineJob('job-name') {
  definition {
    cps {
      script('''
        pipeline {
            agent any
                stages {
                    stage('Stage 1') {
                        steps {
                            echo 'logic'
                        }
                    }
                    stage('Stage 2') {
                        steps {
                            echo 'logic'
                        }
                    }
                }
            }
        }
      '''.stripIndent())
      sandbox()     
    }
  }
}

pipelineJob('github-demo') {
    definition {
        cpsScm {
            scm {
                git {
                    remote {
                        github('jckleiner/learning-and-notes')
                    }
                }
            }
            scriptPath('jenkins/jcasc-2/logic/job1.jenkinsfile')
        }
    }
}